import { ResumeTemplate } from '@/types/resume'

export const resumeTemplates: ResumeTemplate[] = [
  // Professional & Business Templates
  {
    id: 'professional-standard',
    name: 'Professional Standard',
    description: 'Clean, ATS-friendly template perfect for business professionals and managers',
    category: 'modern',
    thumbnail: '/templates/professional-standard-thumb.png',
    previewUrl: '/templates/professional-standard-preview.png',
    isPremium: false,
    features: ['ATS-friendly', 'Clean layout', 'Professional colors', 'Single column'],
    tags: ['professional', 'business', 'manager', 'ats'],
    theme: {
      id: 'professional-standard-theme',
      name: 'Professional Standard',
      colors: {
        primary: '#2563eb',
        secondary: '#1e40af',
        accent: '#3b82f6',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: {
        heading: 'Arial',
        body: 'Arial',
      },
      spacing: 'normal',
      borderRadius: 'none',
      sectionStyle: 'simple'
    },
    layout: {
      columns: 1,
      headerStyle: 'centered',
      sections: ['header', 'summary', 'experience', 'education', 'skills', 'projects'],
    },
    animations: {
      enabled: true,
      entrance: 'fade',
      duration: 0.5,
      delay: 0.1
    },
  },
  {
    id: 'modern-minimalist',
    name: 'Modern Minimalist',
    description: 'Clean and spacious design with modern typography.',
    category: 'modern',
    thumbnail: '/templates/modern.png',
    previewUrl: '/templates/modern-preview.png',
    isPremium: false,
    features: ['Clean Layout', 'Modern Fonts', 'Whitespace Optimized'],
    tags: ['minimalist', 'modern', 'clean'],
    theme: {
      id: 'modern-minimalist-theme',
      name: 'Modern Minimalist',
      colors: {
        primary: '#18181b', // Zinc 900
        secondary: '#27272a', // Zinc 800
        accent: '#52525b', // Zinc 600
        background: '#ffffff',
        text: '#18181b',
        muted: '#71717a', // Zinc 500
      },
      fonts: {
        heading: 'Inter',
        body: 'Inter',
      },
      spacing: 'relaxed',
      borderRadius: 'small',
      sectionStyle: 'minimal'
    },
    layout: {
      columns: 1,
      headerStyle: 'left',
      sections: ['header', 'summary', 'experience', 'education', 'skills', 'projects'],
    },
    animations: {
      enabled: true,
      entrance: 'slide',
      duration: 0.5,
      delay: 0.1
    },
  },
  {
    id: 'bold-header',
    name: 'Bold Header',
    description: 'Strong visual impact with serif headings.',
    category: 'executive',
    thumbnail: '/templates/bold.png',
    previewUrl: '/templates/bold-preview.png',
    isPremium: false,
    features: ['Bold Typography', 'Serif Headings', 'High Contrast'],
    tags: ['bold', 'serif', 'professional'],
    theme: {
      id: 'bold-header-theme',
      name: 'Bold Header',
      colors: {
        primary: '#0f172a', // Slate 900
        secondary: '#1e293b', // Slate 800
        accent: '#334155', // Slate 700
        background: '#ffffff',
        text: '#0f172a',
        muted: '#64748b', // Slate 500
      },
      fonts: {
        heading: 'Playfair Display',
        body: 'Lato',
      },
      spacing: 'compact',
      borderRadius: 'none',
      sectionStyle: 'underlined'
    },
    layout: {
      columns: 1,
      headerStyle: 'centered',
      sections: ['header', 'summary', 'experience', 'education', 'skills', 'projects'],
    },
    animations: {
      enabled: true,
      entrance: 'scale',
      duration: 0.5,
      delay: 0.1
    },
  },
  {
    id: 'creative-accent',
    name: 'Creative Accent',
    description: 'Distinctive color palette for creative roles.',
    category: 'creative',
    thumbnail: '/templates/creative.png',
    previewUrl: '/templates/creative-preview.png',
    isPremium: false,
    features: ['Unique Colors', 'Creative Fonts', 'Standout Design'],
    tags: ['creative', 'colorful', 'unique'],
    theme: {
      id: 'creative-accent-theme',
      name: 'Creative Accent',
      colors: {
        primary: '#7c3aed', // Violet 600
        secondary: '#6d28d9', // Violet 700
        accent: '#8b5cf6', // Violet 500
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: {
        heading: 'Montserrat',
        body: 'Open Sans',
      },
      spacing: 'normal',
      borderRadius: 'medium',
      sectionStyle: 'boxed'
    },
    layout: {
      columns: 1,
      headerStyle: 'left',
      sections: ['header', 'summary', 'experience', 'education', 'skills', 'projects'],
    },
    animations: {
      enabled: true,
      entrance: 'fade',
      duration: 0.5,
      delay: 0.1
    },
  },
  {
    id: 'modern-blue',
    name: 'Modern Blue',
    description: 'A clean, modern template with blue accents perfect for tech professionals',
    category: 'modern',
    thumbnail: '/templates/modern-blue-thumb.png',
    previewUrl: '/templates/modern-blue-preview.png',
    isPremium: false,
    features: ['ATS-friendly', 'Mobile responsive', 'Customizable colors', 'Two-column layout'],
    tags: ['modern', 'clean', 'professional', 'tech'],
    theme: {
      id: 'modern-blue-theme',
      name: 'Modern Blue',
      colors: {
        primary: '#3b82f6',
        secondary: '#1e40af',
        accent: '#06b6d4',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: {
        heading: 'Inter',
        body: 'Inter',
      },
      spacing: 'normal',
      borderRadius: 'medium',
      sectionStyle: 'simple'
    },
    layout: {
      columns: 2,
      headerStyle: 'left',
      sections: [
        {
          id: 'personal-info',
          type: 'personalInfo',
          position: { column: 1, order: 1 },
          visible: true,
          styling: { showIcons: true, showDividers: false, compactMode: false },
        },
        {
          id: 'experience',
          type: 'experience',
          position: { column: 1, order: 2 },
          visible: true,
          styling: { showIcons: true, showDividers: true, compactMode: false },
        },
        {
          id: 'education',
          type: 'education',
          position: { column: 2, order: 1 },
          visible: true,
          styling: { showIcons: true, showDividers: true, compactMode: false },
        },
        {
          id: 'skills',
          type: 'skills',
          position: { column: 2, order: 2 },
          visible: true,
          styling: { showIcons: false, showDividers: false, compactMode: true },
        },
      ],
    },
    animations: {
      enabled: true,
      entrance: 'fade',
      duration: 500,
      delay: 100,
    },
  },
  {
    id: 'minimal-dark',
    name: 'Minimal Dark',
    description: 'Elegant dark theme with minimalist design for creative professionals',
    category: 'minimal',
    thumbnail: '/templates/minimal-dark-thumb.png',
    previewUrl: '/templates/minimal-dark-preview.png',
    isPremium: true,
    features: ['Dark theme', 'Minimalist design', 'Typography focused', 'Creative layout'],
    tags: ['dark', 'minimal', 'creative', 'elegant'],
    theme: {
      id: 'minimal-dark-theme',
      name: 'Minimal Dark',
      colors: {
        primary: '#f8fafc',
        secondary: '#e2e8f0',
        accent: '#8b5cf6',
        background: '#0f172a',
        text: '#f1f5f9',
        muted: '#64748b',
      },
      fonts: {
        heading: 'Playfair Display',
        body: 'Source Sans Pro',
      },
      spacing: 'relaxed',
      borderRadius: 'none',
      sectionStyle: 'minimal'
    },
    layout: {
      columns: 1,
      headerStyle: 'centered',
      sections: [
        {
          id: 'personal-info',
          type: 'personalInfo',
          position: { column: 1, order: 1 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: false },
        },
        {
          id: 'experience',
          type: 'experience',
          position: { column: 1, order: 2 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: false },
        },
        {
          id: 'projects',
          type: 'projects',
          position: { column: 1, order: 3 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: false },
        },
        {
          id: 'skills',
          type: 'skills',
          position: { column: 1, order: 4 },
          visible: true,
          styling: { showIcons: false, showDividers: false, compactMode: true },
        },
      ],
    },
    animations: {
      enabled: true,
      entrance: 'slide',
      duration: 600,
      delay: 150,
    },
  },
  {
    id: 'creative-gradient',
    name: 'Creative Gradient',
    description: 'Vibrant gradient design perfect for designers and creative professionals',
    category: 'creative',
    thumbnail: '/templates/creative-gradient-thumb.png',
    previewUrl: '/templates/creative-gradient-preview.png',
    isPremium: true,
    features: ['Gradient backgrounds', 'Creative layout', 'Portfolio focused', 'Visual appeal'],
    tags: ['creative', 'colorful', 'designer', 'portfolio'],
    theme: {
      id: 'creative-gradient-theme',
      name: 'Creative Gradient',
      colors: {
        primary: '#ec4899',
        secondary: '#8b5cf6',
        accent: '#06b6d4',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: {
        heading: 'Poppins',
        body: 'Open Sans',
      },
      spacing: 'normal',
      borderRadius: 'large',
      sectionStyle: 'boxed'
    },
    layout: {
      columns: 2,
      headerStyle: 'left',
      sections: [
        {
          id: 'personal-info',
          type: 'personalInfo',
          position: { column: 1, order: 1 },
          visible: true,
          styling: { showIcons: true, showDividers: false, compactMode: false },
        },
        {
          id: 'projects',
          type: 'projects',
          position: { column: 1, order: 2 },
          visible: true,
          styling: { showIcons: true, showDividers: true, compactMode: false },
        },
        {
          id: 'experience',
          type: 'experience',
          position: { column: 2, order: 1 },
          visible: true,
          styling: { showIcons: true, showDividers: true, compactMode: false },
        },
        {
          id: 'skills',
          type: 'skills',
          position: { column: 2, order: 2 },
          visible: true,
          styling: { showIcons: false, showDividers: false, compactMode: true },
        },
      ],
    },
    animations: {
      enabled: true,
      entrance: 'scale',
      duration: 700,
      delay: 200,
    },
  },
  {
    id: 'classic-serif',
    name: 'Classic Serif',
    description: 'Traditional serif template perfect for academic and executive positions',
    category: 'classic',
    thumbnail: '/templates/classic-serif-thumb.png',
    previewUrl: '/templates/classic-serif-preview.png',
    isPremium: false,
    features: ['Serif typography', 'Traditional layout', 'Academic friendly', 'Executive style'],
    tags: ['classic', 'traditional', 'academic', 'executive'],
    theme: {
      id: 'classic-serif-theme',
      name: 'Classic Serif',
      colors: {
        primary: '#1f2937',
        secondary: '#374151',
        accent: '#059669',
        background: '#ffffff',
        text: '#111827',
        muted: '#6b7280',
      },
      fonts: {
        heading: 'Crimson Pro',
        body: 'Crimson Pro',
      },
      spacing: 'compact',
      borderRadius: 'small',
      sectionStyle: 'underlined'
    },
    layout: {
      columns: 1,
      headerStyle: 'centered',
      sections: [
        {
          id: 'personal-info',
          type: 'personalInfo',
          position: { column: 1, order: 1 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: true },
        },
        {
          id: 'education',
          type: 'education',
          position: { column: 1, order: 2 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: true },
        },
        {
          id: 'experience',
          type: 'experience',
          position: { column: 1, order: 3 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: true },
        },
        {
          id: 'skills',
          type: 'skills',
          position: { column: 1, order: 4 },
          visible: true,
          styling: { showIcons: false, showDividers: false, compactMode: true },
        },
      ],
    },
    animations: {
      enabled: false,
      entrance: 'fade',
      duration: 300,
      delay: 50,
    },
  },
  {
    id: 'executive-luxury',
    name: 'Executive Luxury',
    description: 'Sophisticated template for senior executives and C-level professionals',
    category: 'executive',
    thumbnail: '/templates/executive-luxury-thumb.png',
    previewUrl: '/templates/executive-luxury-preview.png',
    isPremium: true,
    features: ['Luxury design', 'Executive styling', 'Premium layout', 'Professional appeal'],
    tags: ['executive', 'luxury', 'premium', 'sophisticated'],
    theme: {
      id: 'executive-luxury-theme',
      name: 'Executive Luxury',
      colors: {
        primary: '#92400e',
        secondary: '#451a03',
        accent: '#fbbf24',
        background: '#fefdf9',
        text: '#1c1917',
        muted: '#78716c',
      },
      fonts: {
        heading: 'Cormorant Garamond',
        body: 'Source Sans Pro',
      },
      spacing: 'relaxed',
      borderRadius: 'none',
      sectionStyle: 'minimal'
    },
    layout: {
      columns: 2,
      headerStyle: 'left',
      sections: [
        {
          id: 'personal-info',
          type: 'personalInfo',
          position: { column: 1, order: 1 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: false },
        },
        {
          id: 'experience',
          type: 'experience',
          position: { column: 1, order: 2 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: false },
        },
        {
          id: 'education',
          type: 'education',
          position: { column: 2, order: 1 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: false },
        },
        {
          id: 'certificates',
          type: 'certificates',
          position: { column: 2, order: 2 },
          visible: true,
          styling: { showIcons: false, showDividers: true, compactMode: true },
        },
      ],
    },
    animations: {
      enabled: true,
      entrance: 'fade',
      duration: 400,
      delay: 100,
    },
  },
  // Additional Professional Templates
  {
    id: 'corporate-clean',
    name: 'Corporate Clean',
    description: 'Professional corporate template ideal for finance, consulting, and business roles',
    category: 'classic',
    thumbnail: '/templates/corporate-clean-thumb.png',
    previewUrl: '/templates/corporate-clean-preview.png',
    isPremium: false,
    features: ['Corporate styling', 'Clean typography', 'Professional appeal', 'ATS-friendly'],
    tags: ['corporate', 'finance', 'consulting', 'business'],
    theme: {
      id: 'corporate-clean-theme',
      name: 'Corporate Clean',
      colors: {
        primary: '#1e293b',
        secondary: '#334155',
        accent: '#0f172a',
        background: '#ffffff',
        text: '#0f172a',
        muted: '#64748b',
      },
      fonts: { heading: 'Helvetica', body: 'Helvetica' },
      spacing: 'compact',
      borderRadius: 'none',
      sectionStyle: 'simple'
    },
    layout: {
      columns: 1,
      headerStyle: 'left',
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'skills', type: 'skills', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 200, delay: 0 },
  },
  {
    id: 'tech-modern',
    name: 'Tech Modern',
    description: 'Contemporary template designed specifically for software engineers and developers',
    category: 'modern',
    thumbnail: '/templates/tech-modern-thumb.png',
    previewUrl: '/templates/tech-modern-preview.png',
    isPremium: false,
    features: ['Code-friendly', 'GitHub integration', 'Tech focus', 'Modern design'],
    tags: ['tech', 'developer', 'engineer', 'software'],
    theme: {
      id: 'tech-modern-theme',
      name: 'Tech Modern',
      colors: {
        primary: '#10b981',
        secondary: '#059669',
        accent: '#34d399',
        background: '#ffffff',
        text: '#111827',
        muted: '#6b7280',
      },
      fonts: { heading: 'JetBrains Mono', body: 'Inter' },
      spacing: 'normal',
      borderRadius: 'medium',
      sectionStyle: 'boxed'
    },
    layout: {
      columns: 2,
      headerStyle: 'sidebar',
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: true, showDividers: false, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: true, showDividers: true, compactMode: false } },
        { id: 'projects', type: 'projects', position: { column: 2, order: 1 }, visible: true, styling: { showIcons: true, showDividers: true, compactMode: false } },
        { id: 'skills', type: 'skills', position: { column: 2, order: 2 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
      ],
    },
    animations: { enabled: true, entrance: 'slide', duration: 500, delay: 100 },
  },
  {
    id: 'healthcare-professional',
    name: 'Healthcare Professional',
    description: 'Specialized template for medical professionals, nurses, and healthcare workers',
    category: 'classic',
    thumbnail: '/templates/healthcare-professional-thumb.png',
    previewUrl: '/templates/healthcare-professional-preview.png',
    isPremium: false,
    features: ['Medical focus', 'Certification highlights', 'Clean layout', 'Professional tone'],
    tags: ['healthcare', 'medical', 'nurse', 'doctor'],
    theme: {
      id: 'healthcare-professional-theme',
      name: 'Healthcare Professional',
      colors: {
        primary: '#dc2626',
        secondary: '#b91c1c',
        accent: '#ef4444',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Georgia', body: 'Georgia' },
      spacing: 'normal',
      borderRadius: 'small',
      sectionStyle: 'underlined'
    },
    layout: {
      columns: 1,
      headerStyle: 'centered',
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'education', type: 'education', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'certificates', type: 'certificates', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 300, delay: 50 },
  },
  {
    id: 'creative-designer',
    name: 'Creative Designer',
    description: 'Vibrant template perfect for graphic designers, artists, and creative professionals',
    category: 'creative',
    thumbnail: '/templates/creative-designer-thumb.png',
    previewUrl: '/templates/creative-designer-preview.png',
    isPremium: true,
    features: ['Creative layout', 'Portfolio focus', 'Colorful design', 'Visual appeal'],
    tags: ['creative', 'designer', 'artist', 'portfolio'],
    theme: {
      id: 'creative-designer-theme',
      name: 'Creative Designer',
      colors: {
        primary: '#8b5cf6',
        secondary: '#7c3aed',
        accent: '#a78bfa',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Montserrat', body: 'Open Sans' },
      spacing: 'relaxed',
      borderRadius: 'large',
      sectionStyle: 'boxed'
    },
    layout: {
      columns: 2,
      headerStyle: 'left',
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: true, showDividers: false, compactMode: false } },
        { id: 'projects', type: 'projects', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: true, showDividers: true, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 2, order: 1 }, visible: true, styling: { showIcons: true, showDividers: true, compactMode: false } },
        { id: 'skills', type: 'skills', position: { column: 2, order: 2 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
      ],
    },
    animations: { enabled: true, entrance: 'scale', duration: 600, delay: 150 },
  },
  {
    id: 'academic-researcher',
    name: 'Academic Researcher',
    description: 'Scholarly template ideal for professors, researchers, and PhD candidates',
    category: 'academic',
    thumbnail: '/templates/academic-researcher-thumb.png',
    previewUrl: '/templates/academic-researcher-preview.png',
    isPremium: false,
    features: ['Research focus', 'Publication highlights', 'Academic styling', 'CV format'],
    tags: ['academic', 'research', 'professor', 'phd'],
    theme: {
      id: 'academic-researcher-theme',
      name: 'Academic Researcher',
      colors: {
        primary: '#1e40af',
        secondary: '#1e3a8a',
        accent: '#3b82f6',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Times New Roman', body: 'Times New Roman' },
      spacing: 'compact',
      borderRadius: 'none',
      sectionStyle: 'underlined'
    },
    layout: {
      columns: 1,
      headerStyle: 'centered',
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'certificates', type: 'certificates', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 200, delay: 0 },
  },
  {
    id: 'sales-marketing',
    name: 'Sales & Marketing',
    description: 'Dynamic template for sales professionals and marketing specialists',
    category: 'modern',
    thumbnail: '/templates/sales-marketing-thumb.png',
    previewUrl: '/templates/sales-marketing-preview.png',
    isPremium: false,
    features: ['Results-focused', 'Achievement highlights', 'Dynamic design', 'Sales metrics'],
    tags: ['sales', 'marketing', 'business', 'results'],
    theme: {
      id: 'sales-marketing-theme',
      name: 'Sales & Marketing',
      colors: {
        primary: '#ea580c',
        secondary: '#dc2626',
        accent: '#f97316',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Roboto', body: 'Roboto' },
      spacing: 'normal',
      borderRadius: 'medium',
      sectionStyle: 'simple'
    },
    layout: {
      columns: 2,
      headerStyle: 'left',
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: true, showDividers: false, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: true, showDividers: true, compactMode: false } },
        { id: 'skills', type: 'skills', position: { column: 2, order: 1 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 2, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: true, entrance: 'fade', duration: 400, delay: 100 },
  },
  {
    id: 'entry-level',
    name: 'Entry Level',
    description: 'Student-friendly template perfect for new graduates and entry-level positions',
    category: 'minimal',
    thumbnail: '/templates/entry-level-thumb.png',
    previewUrl: '/templates/entry-level-preview.png',
    isPremium: false,
    features: ['Student-friendly', 'Skills focus', 'Clean design', 'Education highlights'],
    tags: ['student', 'graduate', 'entry-level', 'internship'],
    theme: {
      id: 'entry-level-theme',
      name: 'Entry Level',
      colors: {
        primary: '#059669',
        secondary: '#047857',
        accent: '#10b981',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Verdana', body: 'Verdana' },
      spacing: 'normal',
      borderRadius: 'small',
      sectionStyle: 'minimal'
    },
    layout: {
      columns: 1,
      headerStyle: 'left',
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'education', type: 'education', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'skills', type: 'skills', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 300, delay: 50 },
  },
  {
    id: 'retail-hospitality',
    name: 'Retail & Hospitality',
    description: 'Service-focused template for retail, hospitality, and customer service roles',
    category: 'modern',
    thumbnail: '/templates/retail-hospitality-thumb.png',
    previewUrl: '/templates/retail-hospitality-preview.png',
    isPremium: false,
    features: ['Service focus', 'Customer skills', 'Friendly design', 'Experience highlights'],
    tags: ['retail', 'hospitality', 'service', 'customer'],
    theme: {
      id: 'retail-hospitality-theme',
      name: 'Retail & Hospitality',
      colors: {
        primary: '#7c3aed',
        secondary: '#6d28d9',
        accent: '#8b5cf6',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Calibri', body: 'Calibri' },
      spacing: 'normal',
      borderRadius: 'medium',
      sectionStyle: 'simple'
    },
    layout: {
      columns: 1,
      headerStyle: 'centered',
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'skills', type: 'skills', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: true, entrance: 'fade', duration: 400, delay: 100 },
  },
  {
    id: 'engineering-technical',
    name: 'Engineering & Technical',
    description: 'Technical template for engineers, scientists, and technical professionals',
    category: 'classic',
    thumbnail: '/templates/engineering-technical-thumb.png',
    previewUrl: '/templates/engineering-technical-preview.png',
    isPremium: false,
    features: ['Technical focus', 'Project highlights', 'Clean layout', 'Engineering format'],
    tags: ['engineering', 'technical', 'science', 'mechanical'],
    theme: {
      id: 'engineering-technical-theme',
      name: 'Engineering & Technical',
      colors: {
        primary: '#0f172a',
        secondary: '#1e293b',
        accent: '#334155',
        background: '#ffffff',
        text: '#0f172a',
        muted: '#64748b',
      },
      fonts: { heading: 'Arial', body: 'Arial' },
      spacing: 'compact',
      borderRadius: 'none',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'projects', type: 'projects', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 200, delay: 0 },
  },
  // Additional Professional Templates (Resume.com style)
  {
    id: 'financial-analyst',
    name: 'Financial Analyst',
    description: 'Professional template for financial analysts, accountants, and banking professionals',
    category: 'classic',
    thumbnail: '/templates/financial-analyst-thumb.png',
    previewUrl: '/templates/financial-analyst-preview.png',
    isPremium: false,
    features: ['Finance-focused', 'Analytical skills', 'Clean format', 'ATS-optimized'],
    tags: ['finance', 'analyst', 'banking', 'accounting'],
    theme: {
      id: 'financial-analyst-theme',
      name: 'Financial Analyst',
      colors: {
        primary: '#1e40af',
        secondary: '#1e3a8a',
        accent: '#3b82f6',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Arial', body: 'Arial' },
      spacing: 'compact',
      borderRadius: 'none',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'skills', type: 'skills', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 200, delay: 0 },
  },
  {
    id: 'project-manager',
    name: 'Project Manager',
    description: 'Results-driven template for project managers and team leaders',
    category: 'modern',
    thumbnail: '/templates/project-manager-thumb.png',
    previewUrl: '/templates/project-manager-preview.png',
    isPremium: false,
    features: ['Leadership focus', 'Project highlights', 'Achievement metrics', 'Team management'],
    tags: ['management', 'project', 'leadership', 'agile'],
    theme: {
      id: 'project-manager-theme',
      name: 'Project Manager',
      colors: {
        primary: '#059669',
        secondary: '#047857',
        accent: '#10b981',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Helvetica', body: 'Helvetica' },
      spacing: 'normal',
      borderRadius: 'small',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'projects', type: 'projects', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'education', type: 'education', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 300, delay: 50 },
  },
  {
    id: 'administrative-assistant',
    name: 'Administrative Assistant',
    description: 'Professional template for administrative and office support roles',
    category: 'classic',
    thumbnail: '/templates/administrative-assistant-thumb.png',
    previewUrl: '/templates/administrative-assistant-preview.png',
    isPremium: false,
    features: ['Office skills', 'Organization focus', 'Professional appeal', 'Clean layout'],
    tags: ['administrative', 'office', 'support', 'clerical'],
    theme: {
      id: 'administrative-assistant-theme',
      name: 'Administrative Assistant',
      colors: {
        primary: '#7c3aed',
        secondary: '#6d28d9',
        accent: '#8b5cf6',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Times New Roman', body: 'Times New Roman' },
      spacing: 'compact',
      borderRadius: 'none',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'skills', type: 'skills', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 200, delay: 0 },
  },
  {
    id: 'teacher-educator',
    name: 'Teacher & Educator',
    description: 'Educational template for teachers, professors, and training professionals',
    category: 'classic',
    thumbnail: '/templates/teacher-educator-thumb.png',
    previewUrl: '/templates/teacher-educator-preview.png',
    isPremium: false,
    features: ['Education focus', 'Teaching experience', 'Certification highlights', 'Professional tone'],
    tags: ['teacher', 'education', 'professor', 'training'],
    theme: {
      id: 'teacher-educator-theme',
      name: 'Teacher & Educator',
      colors: {
        primary: '#1e40af',
        secondary: '#1e3a8a',
        accent: '#3b82f6',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Georgia', body: 'Georgia' },
      spacing: 'normal',
      borderRadius: 'small',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'education', type: 'education', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'certificates', type: 'certificates', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 300, delay: 50 },
  },
  {
    id: 'human-resources',
    name: 'Human Resources',
    description: 'Professional template for HR specialists, recruiters, and people operations',
    category: 'modern',
    thumbnail: '/templates/human-resources-thumb.png',
    previewUrl: '/templates/human-resources-preview.png',
    isPremium: false,
    features: ['HR expertise', 'People skills', 'Policy knowledge', 'Professional design'],
    tags: ['hr', 'recruiting', 'people', 'operations'],
    theme: {
      id: 'human-resources-theme',
      name: 'Human Resources',
      colors: {
        primary: '#dc2626',
        secondary: '#b91c1c',
        accent: '#ef4444',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Calibri', body: 'Calibri' },
      spacing: 'normal',
      borderRadius: 'medium',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'skills', type: 'skills', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: true, entrance: 'fade', duration: 400, delay: 100 },
  },
  {
    id: 'customer-service',
    name: 'Customer Service',
    description: 'Service-oriented template for customer service representatives and support roles',
    category: 'modern',
    thumbnail: '/templates/customer-service-thumb.png',
    previewUrl: '/templates/customer-service-preview.png',
    isPremium: false,
    features: ['Service excellence', 'Communication skills', 'Problem solving', 'Customer focus'],
    tags: ['customer', 'service', 'support', 'communication'],
    theme: {
      id: 'customer-service-theme',
      name: 'Customer Service',
      colors: {
        primary: '#059669',
        secondary: '#047857',
        accent: '#10b981',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Verdana', body: 'Verdana' },
      spacing: 'normal',
      borderRadius: 'small',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'skills', type: 'skills', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 300, delay: 50 },
  },
  {
    id: 'operations-manager',
    name: 'Operations Manager',
    description: 'Strategic template for operations managers and business leaders',
    category: 'executive',
    thumbnail: '/templates/operations-manager-thumb.png',
    previewUrl: '/templates/operations-manager-preview.png',
    isPremium: true,
    features: ['Leadership focus', 'Strategic planning', 'Process improvement', 'Executive style'],
    tags: ['operations', 'management', 'strategy', 'leadership'],
    theme: {
      id: 'operations-manager-theme',
      name: 'Operations Manager',
      colors: {
        primary: '#1e293b',
        secondary: '#334155',
        accent: '#0f172a',
        background: '#ffffff',
        text: '#0f172a',
        muted: '#64748b',
      },
      fonts: { heading: 'Helvetica', body: 'Helvetica' },
      spacing: 'relaxed',
      borderRadius: 'none',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: false } },
        { id: 'education', type: 'education', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'certificates', type: 'certificates', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: true, entrance: 'fade', duration: 400, delay: 100 },
  },
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    description: 'Analytics-focused template for data scientists and machine learning engineers',
    category: 'modern',
    thumbnail: '/templates/data-scientist-thumb.png',
    previewUrl: '/templates/data-scientist-preview.png',
    isPremium: false,
    features: ['Technical expertise', 'Research focus', 'Analytics skills', 'Modern design'],
    tags: ['data', 'analytics', 'machine-learning', 'python'],
    theme: {
      id: 'data-scientist-theme',
      name: 'Data Scientist',
      colors: {
        primary: '#7c3aed',
        secondary: '#6d28d9',
        accent: '#8b5cf6',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Arial', body: 'Arial' },
      spacing: 'normal',
      borderRadius: 'medium',
    },
    layout: {
      columns: 2,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: true, showDividers: false, compactMode: false } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: true, showDividers: true, compactMode: false } },
        { id: 'projects', type: 'projects', position: { column: 2, order: 1 }, visible: true, styling: { showIcons: true, showDividers: true, compactMode: false } },
        { id: 'skills', type: 'skills', position: { column: 2, order: 2 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
      ],
    },
    animations: { enabled: true, entrance: 'slide', duration: 500, delay: 100 },
  },
  {
    id: 'legal-professional',
    name: 'Legal Professional',
    description: 'Professional template for lawyers, paralegals, and legal professionals',
    category: 'classic',
    thumbnail: '/templates/legal-professional-thumb.png',
    previewUrl: '/templates/legal-professional-preview.png',
    isPremium: true,
    features: ['Legal expertise', 'Professional tone', 'Traditional format', 'Credibility focus'],
    tags: ['legal', 'lawyer', 'paralegal', 'law'],
    theme: {
      id: 'legal-professional-theme',
      name: 'Legal Professional',
      colors: {
        primary: '#1e293b',
        secondary: '#334155',
        accent: '#0f172a',
        background: '#ffffff',
        text: '#0f172a',
        muted: '#64748b',
      },
      fonts: { heading: 'Times New Roman', body: 'Times New Roman' },
      spacing: 'compact',
      borderRadius: 'none',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'education', type: 'education', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'certificates', type: 'certificates', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 200, delay: 0 },
  },
  {
    id: 'construction-trades',
    name: 'Construction & Trades',
    description: 'Skilled trades template for construction, electrical, plumbing professionals',
    category: 'classic',
    thumbnail: '/templates/construction-trades-thumb.png',
    previewUrl: '/templates/construction-trades-preview.png',
    isPremium: false,
    features: ['Skills-based', 'Certification focus', 'Safety emphasis', 'Experience highlights'],
    tags: ['construction', 'trades', 'electrical', 'plumbing'],
    theme: {
      id: 'construction-trades-theme',
      name: 'Construction & Trades',
      colors: {
        primary: '#ea580c',
        secondary: '#dc2626',
        accent: '#f97316',
        background: '#ffffff',
        text: '#1f2937',
        muted: '#6b7280',
      },
      fonts: { heading: 'Arial', body: 'Arial' },
      spacing: 'compact',
      borderRadius: 'small',
    },
    layout: {
      columns: 1,
      sections: [
        { id: 'personal-info', type: 'personalInfo', position: { column: 1, order: 1 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'skills', type: 'skills', position: { column: 1, order: 2 }, visible: true, styling: { showIcons: false, showDividers: false, compactMode: true } },
        { id: 'experience', type: 'experience', position: { column: 1, order: 3 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
        { id: 'certificates', type: 'certificates', position: { column: 1, order: 4 }, visible: true, styling: { showIcons: false, showDividers: true, compactMode: true } },
      ],
    },
    animations: { enabled: false, entrance: 'fade', duration: 200, delay: 0 },
  },
]

export const getTemplateById = (id: string): ResumeTemplate | undefined => {
  return resumeTemplates.find(template => template.id === id)
}

export const getTemplatesByCategory = (category: ResumeTemplate['category']): ResumeTemplate[] => {
  return resumeTemplates.filter(template => template.category === category)
}

export const getFreeTemplates = (): ResumeTemplate[] => {
  return resumeTemplates.filter(template => !template.isPremium)
}

export const getPremiumTemplates = (): ResumeTemplate[] => {
  return resumeTemplates.filter(template => template.isPremium)
}